name: VuePress CI/CD
on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件
jobs:
  # 任务1 ： 构建项目到 master 分支，并且部署pages服务。
  build_and_deploy:
    runs-on: ubuntu-latest   # 底层的系统镜像
    steps:
      # 步骤1：检出代码到工作目录
      - name: Checkout Code
        uses: actions/checkout@v2


      # /home/runner/work/english/english
      # 步骤2：安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'

      # 步骤3：安装项目依赖
      - name: Show Main Branch
        run: |
          pwd
          tree   

      # 构建main 分支的源码
      - name: Install Dependencies And Build VuePress
        run: |
          npm install
          npm run build

      # 构建结果提交 Main
      - name: Main branch
        run: |
          git config user.name "triggergun"
          git config user.email "930572358@qq.com"
          git add .
          git commit -m "Build commit"
          git remote add origin_with_token_with_branch https://github.com/triggergun/english.git
          git push origin_with_token_with_branch main
          cp  -r docs/.vuepress/dist ../build  # 将构建的源码copy到上一级目录。指在当前的虚拟机里面的目录



      # 拉取分支并。 展示全部的分支。
      - name: Pull branch
        run: |
          git fetch
          git checkout master
          git branch -a


      - name: Show Pwd01
        run: |
          pwd
          tree

      # 在当前系统上
      - name: Copy Build Results to Master Branch
        run: |
          cp -r ../build/* .  # 复制构建源码结果到工作目录到当前的master下
          rm -rf ./node_modules  # 删除依赖包

      - name: Show Pwd02
        run: |
          pwd
          tree


      # 提交 master 分支
      - name: Commit Master
        run: |
          git add .
          git commit -m "Update master with latest build results"
          git push origin_with_token_with_branch master  # 推送构建结果到 master 分支,master 是可以直接部署的网页源码。